version: '3'

tasks:
  start:
    deps: [build]
    cmds:
      - "docker compose up -d"
    desc: Runs the Spring Boot application

  build:
    cmds:
      - mvn spring-boot:build-image -DskipTests
    desc: Builds the project with Maven

  stop:
    cmds:
      - "docker compose stop"
      - "docker compose rm -f"
    desc: Stops the Spring Boot application

  restart:
    cmds:
      - task: stop
      - task: start
    desc: Restarts the Spring Boot application