name: Resume Service

on:
  push:
    paths:
      - resume-service/**
    branches:
      - '**'

jobs:
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/resume-service

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven Wrapper Executable
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw -ntp clean verify

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          ./mvnw spring-boot:build-image -DskipTests \
            -Dspring-boot.build-image.imageName=$DOCKER_IMAGE_NAME
          echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
          docker push $DOCKER_IMAGE_NAME
